parameters:
  dependsOn: build_projection

jobs:
- job: sign_projection
  dependsOn: ${{ parameters.dependsOn }}
  pool:
    name: Package ES Lab E
  steps:
  - task: DownloadBuildArtifacts@0 
    displayName: 'Download artifact: projection'
    inputs: 
      buildType: 'current'
      downloadType: single
      artifactName: projection
      downloadPath: '$(Build.ArtifactStagingDirectory)'

  - task: PkgESCodeSign@10
    displayName: CodeSign
    inputs:
      signConfigXml: '$(Build.SourcesDirectory)/src/package/pywinrt/projection/SignConfig.xml'
      inPathRoot: '$(Build.ArtifactStagingDirectory)/projection/amd64'
      outPathRoot: '$(Build.ArtifactStagingDirectory)/projection/amd64'

  - task: PkgESCodeSign@10
    displayName: CodeSign
    inputs:
      signConfigXml: '$(Build.SourcesDirectory)/src/package/pywinrt/projection/SignConfig.xml'
      inPathRoot: '$(Build.ArtifactStagingDirectory)/projection/x86'
      outPathRoot: '$(Build.ArtifactStagingDirectory)/projection/x86'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifact: projection'
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)/projection
      artifactName: projection
