jobs:
- job: build_pywinrt
  pool:
    vmImage: 'windows-2019'

  steps:
  - script: |
      @echo off
      @echo Build.BuildNumber $(Build.BuildNumber)
      @echo buildFullProjection $(buildFullProjection)

  - template: task-vsdevcmd.yml
    parameters:
      buildArchitecture: 'x86'  
      hostArchitecture: 'x86'

  - task: CMake@1
    displayName: 'Generate xlang build files via cmake'
    inputs:
      cwd: '.'
      cmakeArgs: -S src -B_build -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl -DXLANG_BUILD_VERSION=0.9.$(Build.BuildNumber)

  - task: CMake@1
    displayName: 'build pywinrt'
    inputs:
      cwd: '.'
      cmakeArgs: --build .\_build -- -v pywinrt

  - task: CopyFiles@2
    inputs:
      sourceFolder: _build\tool\python\
      contents: pywinrt.exe
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifact: pywinrt'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'pywinrt'