parameters:
  dependsOn: 'build_projection'
  downloadArtifactName: 'projection'
  publishArtifactName: 'signed-projection'

jobs:
- job: sign_projection
  dependsOn: ${{ parameters.dependsOn }}
  pool:
    name: Package ES Lab E
  steps:
  - task: DownloadBuildArtifacts@0 
    displayName: 'Download artifact: ${{ parameters.downloadArtifactName }}'
    inputs: 
      buildType: 'current'
      downloadType: single
      artifactName: ${{ parameters.downloadArtifactName }}
      downloadPath: '$(Build.ArtifactStagingDirectory)'

  - template: steps-sign-projection.yml
    parameters:
      architecture: x86  
      artifactName: ${{ parameters.downloadArtifactName }}
      publishArtifactName: ${{ parameters.publishArtifactName }}

  - template: steps-sign-projection.yml
    parameters:
      architecture: amd64  
      artifactName: ${{ parameters.downloadArtifactName }}
      publishArtifactName: ${{ parameters.publishArtifactName }}

  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifact: ${{ parameters.publishArtifactName }}'
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)/${{ parameters.publishArtifactName }}
      artifactName: ${{ parameters.publishArtifactName }}

