pool:

  name: windows-2019

  demands:

  - Cmd

  - cmake



steps:

- script: |
   @echo off
   
   set vswherepath="%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe"
   for /f "usebackq delims=" %%i in (`%vswherepath% -latest -property installationPath`) do (
     set vslatest="%%i"
     if exist "%%i\Common7\Tools\vsdevcmd.bat" (
       set vsdevcmd="%%i\Common7\Tools\vsdevcmd.bat"
     )
   )
   
   @echo vslatest %vslatest%
   @echo vsdevcmd %vsdevcmd%
   
   @echo ##vso[task.setvariable variable=vslatest]%vslatest%
   @echo ##vso[task.setvariable variable=vsdevcmd]%vsdevcmd%

  displayName: 'locate vsdevcmd via vswhere'



- task: BatchScript@1

  displayName: 'Run script src/scripts/windows/call-batchfile.bat'

  inputs:

    filename: 'src/scripts/windows/call-batchfile.bat'

    arguments: '%vsdevcmd% -host_arch=amd64 -arch=x86'

    modifyEnvironment: true



- task: CMake@1

  displayName: 'CMake -S src -B_build -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl'

  inputs:

    cmakeArgs: '-S src -B_build -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl'



- task: CMake@1

  displayName: 'CMake --build .\_build\ -- -v pywinrt'

  inputs:

    cmakeArgs: '--build .\_build\ -- -v pywinrt'



- task: NuGetCommand@2

  displayName: 'NuGet install Microsoft.Windows.CppWinRT'

  inputs:

    command: custom

    arguments: 'install Microsoft.Windows.CppWinRT -ExcludeVersion -OutputDirectory _tools'



- task: NuGetCommand@2

  displayName: 'NuGet install python'

  inputs:

    command: custom

    arguments: 'install python -ExcludeVersion  -OutputDirectory src\package\pywinrt\projection\'



- script: |
   _tools\Microsoft.Windows.CppWinRT\bin\cppwinrt.exe -in 10.0.17763.0 -out src\package\pywinrt\projection\cppwinrt -verbose
   _build\tool\python\pywinrt.exe -in 10.0.17763.0 -out src\package\pywinrt\projection\pywinrt -verbose -include Windows.Foundation -include Windows.Data.Json -include Windows.Devices.Geolocation -exclude Windows.UI.Comp -exclude Windows.UI.Xaml

  displayName: 'Generate Projections'



- task: BatchScript@1

  displayName: 'Run script src/scripts/windows/call-batchfile.bat'

  inputs:

    filename: 'src/scripts/windows/call-batchfile.bat'

    arguments: '%vsdevcmd% -host_arch=amd64 -arch=amd64'

    modifyEnvironment: true



- task: CMake@1

  displayName: 'CMake -S src/package/pywinrt/projection -B_build.projection -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl'

  inputs:

    cmakeArgs: '-S src/package/pywinrt/projection -B_build.projection -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl'



- task: CMake@1

  displayName: 'CMake --build .\_build.projection\ -- -v '

  inputs:

    cmakeArgs: '--build .\_build.projection\ -- -v '


