jobs:
- job: PyWinRT_exe
  pool:
    vmImage: 'windows-2019'

  steps:
  - script: |
      @echo off
      
      set vswherepath="%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe"
      for /f "usebackq delims=" %%i in (`%vswherepath% -latest -property installationPath`) do (
        set vslatest="%%i"
        if exist "%%i\Common7\Tools\vsdevcmd.bat" (
          set vsdevcmd="%%i\Common7\Tools\vsdevcmd.bat"
        )
      )
      
      @echo vslatest %vslatest%
      @echo vsdevcmd %vsdevcmd%
      
      @echo ##vso[task.setvariable variable=vslatest]%vslatest%
      @echo ##vso[task.setvariable variable=vsdevcmd]%vsdevcmd%
    displayName: 'locate vsdevcmd via vswhere'

  - task: BatchScript@1
    displayName: 'Configure environment with VSDevCmd (arch x86/host x86)'
    inputs:
      filename: $(vsdevcmd)
      arguments: -host_arch=x86 -arch=x86
      modifyEnvironment: true

  - task: CMake@1
    displayName: 'Generate xlang build files via cmake'
    inputs:
      cwd: '.'
      cmakeArgs: -S src -B_build -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl

  - task: CMake@1
    displayName: 'build pywinrt'
    inputs:
      cwd: '.'
      cmakeArgs: --build .\_build -- -v pywinrt

  - task: CopyFiles@2
    inputs:
      sourceFolder: _build/tool/python
      contents: pywinrt.exe
      targetFolder: $(Build.ArtifactStagingDirectory)

