jobs:
- template: AzurePipelinesTemplates/job-generate-projection.yml

- job: build_projection
  dependsOn: generate_projection
  pool:
    vmImage: 'windows-2019'
  timeoutInMinutes: 120
  strategy:
    maxParallel: 10
    matrix:
      Release_x86:
        buildArchitecture: 'x86'
        buildConfiguration: 'Release'
      Release_x64:
        buildArchitecture: 'amd64'
        buildConfiguration: 'Release'
  steps:    
  - template: AzurePipelinesTemplates/steps-build-projection.yml
    parameters:
      architecture: $(buildArchitecture)  
      pythonVersionSpec: '3.7.x'

- job: sign_projection
  dependsOn: build_projection
  pool:
    vmImage: 'windows-2019'
  steps:
  - task: DownloadBuildArtifacts@0 
    inputs: 
      buildType: 'current'
      downloadType: single
      artifactName: projection
      downloadPath: '$(Build.ArtifactStagingDirectory)'

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.ArtifactStagingDirectory)/projection'
      contents: '*'
      targetFolder: $(Build.ArtifactStagingDirectory)/signed-projection

  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifact: signed-projection'
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)/signed-projection
      artifactName: signed-projection

- template: AzurePipelinesTemplates/job-package-projection.yml
  parameters:
    dependsOn: sign_projection
    artifactName: signed-projection
