name: $(Date:yyMMdd)$(Rev:.r)
jobs:
- job: dump_debug
  - script: echo $(ProjectionType)
  - script: echo $(variables['ProjectionType'])

- template: AzurePipelinesTemplates/job-build-pywinrt.yml

- template: AzurePipelinesTemplates/job-build-projection.yml
  ${{ if eq(variables['ProjectionType'], 'full') }}:
    parameters:
      buildFullProjection: true

- template: AzurePipelinesTemplates/job-package-projection.yml
  parameters:
    dependsOn: build_projection
