name: $(System.TeamProject)_$(BuildID).$(Date:yyMMdd).$(Date:MMdd).$(DayOfYear).$(Rev:rrr)
jobs:
- template: AzurePipelinesTemplates/job-build-pywinrt.yml

- template: AzurePipelinesTemplates/job-build-projection.yml

- template: AzurePipelinesTemplates/job-package-projection.yml
  parameters:
    dependsOn: build_projection
